# Generated by Django 4.2.2 on 2023-07-08 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('street_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('availability', models.BooleanField()),
                ('max_num_children', models.IntegerField()),
                ('max_num_adults', models.IntegerField()),
                ('allow_pet', models.BooleanField()),
                ('descrpition', models.CharField(max_length=500)),
            ],
        ),
    ]
