# Generated by Django 4.2.2 on 2023-07-08 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0001_initial'),
        ('homestays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homestay_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homestay',
            name='pricing_config_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homestay_pricing_config', to='myadmin.pricingconfig'),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='descrpition',
            field=models.TextField(),
        ),
    ]
