# Generated by Django 4.2.2 on 2023-07-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0002_homestay_manager_id_homestay_pricing_config_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homestay',
            old_name='descrpition',
            new_name='description',
        ),
    ]
