# Generated by Django 4.2.2 on 2023-07-15 06:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0005_alter_homestay_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
