# Generated by Django 4.2.2 on 2023-06-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_percentage', models.FloatField()),
                ('cancellation_refund_percentage', models.FloatField()),
                ('free_cancellation_days', models.IntegerField()),
                ('discount', models.FloatField()),
            ],
        ),
    ]
