# Generated by Django 4.2.2 on 2023-07-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
