# Generated by Django 4.2.2 on 2023-07-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_pricingconfig_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
