# Generated by Django 4.2.2 on 2023-07-14 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homestays', '0005_alter_homestay_manager_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(null=True)),
                ('checkout_date', models.DateField(null=True)),
                ('num_adults', models.IntegerField(null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('deposit_price', models.FloatField(blank=True, null=True)),
                ('refund_price', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('REFUNDED', 'Refunded')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_children', models.IntegerField(default=0, null=True)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestays.homestay')),
                ('services', models.ManyToManyField(limit_choices_to={'homestay_id': django.db.models.expressions.OuterRef('homestay')}, to='homestays.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
