# Generated by Django 4.2.2 on 2023-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], default='Pending', max_length=20),
        ),
    ]
