# Generated by Django 4.2.2 on 2023-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0005_alter_homestay_manager_id_and_more'),
        ('bookings', '0002_alter_booking_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='homestays.service'),
        ),
    ]
